/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1 "github.com/googlecloudplatform/gcs-fuse-csi-driver/pkg/apis/datalayer.gke.io/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGCPDataSources implements GCPDataSourceInterface
type FakeGCPDataSources struct {
	Fake *FakeDatalayerV1
	ns   string
}

var gcpdatasourcesResource = v1.SchemeGroupVersion.WithResource("gcpdatasources")

var gcpdatasourcesKind = v1.SchemeGroupVersion.WithKind("GCPDataSource")

// Get takes name of the gCPDataSource, and returns the corresponding gCPDataSource object, and an error if there is any.
func (c *FakeGCPDataSources) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.GCPDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gcpdatasourcesResource, c.ns, name), &v1.GCPDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPDataSource), err
}

// List takes label and field selectors, and returns the list of GCPDataSources that match those selectors.
func (c *FakeGCPDataSources) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GCPDataSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gcpdatasourcesResource, gcpdatasourcesKind, c.ns, opts), &v1.GCPDataSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.GCPDataSourceList{ListMeta: obj.(*v1.GCPDataSourceList).ListMeta}
	for _, item := range obj.(*v1.GCPDataSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gCPDataSources.
func (c *FakeGCPDataSources) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gcpdatasourcesResource, c.ns, opts))

}

// Create takes the representation of a gCPDataSource and creates it.  Returns the server's representation of the gCPDataSource, and an error, if there is any.
func (c *FakeGCPDataSources) Create(ctx context.Context, gCPDataSource *v1.GCPDataSource, opts metav1.CreateOptions) (result *v1.GCPDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gcpdatasourcesResource, c.ns, gCPDataSource), &v1.GCPDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPDataSource), err
}

// Update takes the representation of a gCPDataSource and updates it. Returns the server's representation of the gCPDataSource, and an error, if there is any.
func (c *FakeGCPDataSources) Update(ctx context.Context, gCPDataSource *v1.GCPDataSource, opts metav1.UpdateOptions) (result *v1.GCPDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gcpdatasourcesResource, c.ns, gCPDataSource), &v1.GCPDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPDataSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGCPDataSources) UpdateStatus(ctx context.Context, gCPDataSource *v1.GCPDataSource, opts metav1.UpdateOptions) (*v1.GCPDataSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gcpdatasourcesResource, "status", c.ns, gCPDataSource), &v1.GCPDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPDataSource), err
}

// Delete takes name of the gCPDataSource and deletes it. Returns an error if one occurs.
func (c *FakeGCPDataSources) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gcpdatasourcesResource, c.ns, name, opts), &v1.GCPDataSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGCPDataSources) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gcpdatasourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.GCPDataSourceList{})
	return err
}

// Patch applies the patch and returns the patched gCPDataSource.
func (c *FakeGCPDataSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GCPDataSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gcpdatasourcesResource, c.ns, name, pt, data, subresources...), &v1.GCPDataSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.GCPDataSource), err
}
